API/API/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('view.urls', 'view'), namespace='view')),
    path('admin/', admin.site.urls),
]

API/view/urls.py
from django.urls import path, re_path
from .views import result, watching, index

urlpatterns = [
    path('', index, name='home'),
    path('results/', result, name='results'),
    path('watch/<slug:video_id>', watching, name='watch')
]

API/view/models.py
from django.db import models

# Create your models here.

API/view/views.py
from django.shortcuts import render, reverse, HttpResponseRedirect
from apiclient.discovery import build


def result(request, *args, **kargs):
    if request.method == "POST":
        contents = get_result(key=request.POST['key'])
        return render(request, 'view/result.html', contents)
    return HttpResponseRedirect(reverse('view:home'))


def search_videos(options):
    DEVELOPER_KEY = "AIzaSyCXMDV4kLIWAQxsv4oM_2p1ZlrVerIKbVM"
    YOUTUBE_API_SERVICE_NAME = "youtube"
    YOUTUBE_API_VERSION = "v3"

    youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION,
                    developerKey=DEVELOPER_KEY)

    # Call the search.list method to retrieve results matching the specified
    # query term.
    search_response = youtube.search().list(
        q=options["key"],
        part="id,snippet",
        maxResults=options["max_results"]
    ).execute()

    contexts = []

    # Add each result to the appropriate list, and then display the lists of
    # matching videos, channels, and playlists.
    for search_result in search_response.get("items", []):
        if search_result["id"]["kind"] == "youtube#video":
            # videos.append("%s (%s)" % (search_result["snippet"]["title"],
            #                            search_result["id"]["videoId"]))
            contexts.append({
                'title': search_result["snippet"]["title"],
                'video_id': search_result["id"]["videoId"],
                'thumbnail': search_result["snippet"]["thumbnails"]["high"]["url"],
                'description': search_result['snippet']['description']
            })
    return contexts


def watching(request, video_id):
    return render(request, "view/watch.html", {
        "video_id": video_id
    })


def get_result(key=None, max_results=25):
    options = {
        "key": key,
        "max_results": max_results
    }
    return {
        "result_videos": search_videos(options)
    }


def index(request, *args, **kargs):
    contents = get_result()
    return render(request, 'view/result.html', contents)

API/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Youtube API</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% include 'partials/_navbar.html' %}
    {% block context %}
        Hello world
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

API/templates/partials/_navbar.html
<form class="navbar-form navbar-left" role="search" method="POST" action="{% url 'view:results' %}">
  {% csrf_token %}
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search" name='key'>
  </div>
</form>

API/view/templates/view/index.html
{% extends 'base.html' %}

{% block context %}
<div class="container">
    {% if not result_videos %}
      <h2 class="my-7">No video avaiable match your searching
      </h2>
    
    {% else %}
      {% for video in result_videos %}
        <div class="row">
          <div class="col-md-4">
            <a href="{% url 'view:watch' video.video_id %}">
              <img class="img-fluid rounded" src="{{ video.thumbnail }}" alt="">
            </a>
          </div>
          <div class="col-md-7">
            <h4>{{ video.title }}</h4>
            <p> Description of videos</p>
          </div>
        </div>
        <hr>
        
      {% endfor %}
    
    {% endif %}
</div>
{% endblock %}

API/view/templates/view/result.html
{% extends 'base.html' %}

{% block context %}
<div class="container">
    {% if not result_videos %}
      <h2 class="my-7">No video avaiable match your searching
      </h2>
    
    {% else %}
      {% for video in result_videos %}
        <div class="row">
          <div class="col-md-4">
            <a href="{% url 'view:watch' video.video_id %}">
              <img class="img-fluid rounded" src="{{ video.thumbnail }}" alt="">
            </a>
          </div>
          <div class="col-md-7">
            <a class="btn btn-default" href="{% url 'view:watch' video.video_id %}" 
            style="font-size: 25px; padding: 0; text-align: left">{{ video.title }}</a>
            <p> {{ video.description }}</p>
          </div>
        </div>
        <hr>
        
      {% endfor %}
    
    {% endif %}
</div>
{% endblock %}

API/view/templates/view/watch.html
<div class="row">
    <div class="col-md-10">
        <iframe width="1200" height="800" 
            src="https://www.youtube-nocookie.com/embed/{{ video_id }}" 
            frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
        </iframe>
    </div>
    
<div>